### PR TITLE
Updates the $PATH varible documentation

### PR DESCRIPTION
**Pull request by anweshadas**
Adds the more information about how $PATH variable works.
It shows how to use which command to see $PATH working

### CODE REVIEW

**Review by jasonbraganza — APPROVED** [review]
:+1:

**Review by kushaldas — CHANGES_REQUESTED** [review]
This section is broken

lym_files_html_broken

I think the paths are supposed to be shown in a list, here HTML is rendering them in a single line.

**Comment by jasonbraganza** [comment]
ok i agree with @kushaldas. 
@anweshadas please can you make it look list like? :)

**Comment by anweshadas** [comment]
> ok i agree with @kushaldas.
> @anweshadas please can you make it look list like? :)

Pushed the new changes please have a look at it.

**Review by SaptakS — APPROVED** [review]
This looks good to me now

**Pull request merged**
